### ISSUE TITLE
关于Shopee-Price Match Guarantee竞赛数据处理的问题

### ISSUE THREAD

**Issue by JDZW2014** [DLLXW/data-science-competition#27]
您好，小白想请教一个问题：我有考虑过依据数据的 label_group 对数据进行采样生成类似于 （image1, image2, label）的数据，然后进行二分类训练，但是我看大佬们的方案都不是这么做的，想请问下这样做会有什么问题吗？ 非常感谢！！！

**Comment by DLLXW** [comment]
好像有方案是这么做的，而且效果还挺好，你找找那个前排的分享。


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月30日 09:40:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [DLLXW/data-science-competition] 关于Shopee-Price Match Guarantee竞赛数据处理的问题 (#27)




 
您好，小白想请教一个问题：我有考虑过依据数据的 label_group 对数据进行采样生成类似于 （image1, image2, label）的数据，然后进行二分类训练，但是我看大佬们的方案都不是这么做的，想请问下这样做会有什么问题吗？ 非常感谢！！！
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JDZW2014** [comment]
哦哦，我找一下，非常感谢！！！
另外想问一下大佬选用了目前的方案而没有采用这种二分类的方式是有什么思考吗？
